//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DTO
{
    public class ChiTietHoaDonBanHang
    {
        public string maCTHDBH { get; set; }

        public string maHDBH
        {
            get;
            set;
        }

        public string maHangHoa
        {
            get;
            set;
        }

        public int soLuong
        {
            get;
            set;
        }

        public double donGia
        {
            get;
            set;
        }

        public float chietKhau
        {
            get;
            set;
        }

        public double thanhTien
        {
            get;
            set;
        }
        public ChiTietHoaDonBanHang()
        {

        }

        public ChiTietHoaDonBanHang(string _maCTHDBH, string _maHDBH, string _maHangHoa, int _soLuong, double _donGia, float _chietKhau, double _thanhTien)
        {
            this.maCTHDBH = _maCTHDBH;
            this.maHDBH = _maHDBH;
            this.maHangHoa = _maHangHoa;
            this.soLuong = _soLuong;
            this.donGia = _donGia;
            this.chietKhau = _chietKhau;
            this.thanhTien = _thanhTien;
        }
    }

}

