//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DTO
{
    public class ChiTietHoaDonMuaHang
    {
        public string maCTHDMH
        {
            get;
            set;
        }

        public string maHDMH
        {
            get;
            set;
        }

        public string maHangHoa
        {
            get;
            set;
        }

        public int soLuong
        {
            get;
            set;
        }

        public double thanhTien
        {
            get;
            set;
        }

        public double donGia
        {
            get;
            set;
        }
        public ChiTietHoaDonMuaHang()
        {

        }

        public ChiTietHoaDonMuaHang(){}
        public ChiTietHoaDonMuaHang(string _maCTHDMH, string _maHDMH, string _maHangHoa, int _soLuong, double _donGia, double _thanhTien) 
        {
            this.maCTHDMH = _maCTHDMH;
            this.maHDMH = _maHDMH;
            this.maHangHoa = _maHangHoa;
            this.soLuong = _soLuong;
            this.donGia = _donGia;
            this.thanhTien = _thanhTien;
        }
    }
}


