//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DTO
{
    public class Hang
    {
        public string maHang
        {
            get;
            set;
        }

        public string tenHang
        {
            get;
            set;
        }
        public Hang()
        {

        }

        public Hang(string _maHang, string _tenHang)
        {
            this.maHang = _maHang;
            this.tenHang = _tenHang;
        }
    }
}


