//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DTO
{
    public class HangHoa
    {
        public string maHangHoa
        {
            get;
            set;
        }

        public string maLoaiHangHoa
        {
            get;
            set;
        }

        public int soLuong
        {
            get;
            set;
        }

        public string baoHanh
        {
            get;
            set;
        }

        public double giaMua
        {
            get;
            set;
        }

        public double giaBan
        {
            get;
            set;
        }
        public HangHoa()
        {

        }

        public HangHoa(string _maHangHoa, string _maLoaiHangHoa, int _soLuong, string _baoHanh, double _giaMua, double _giaBan)
        {
            this.maHangHoa = _maHangHoa;
            this.maLoaiHangHoa = _maLoaiHangHoa;
            this.soLuong = _soLuong;
            this.baoHanh = _baoHanh;
            this.giaMua = _giaMua;
            this.giaBan = _giaBan;
        }
    }
}


