//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DTO
{
    public class HangHoa
    {
        public string maHangHoa
        {
            get;
            set;
        }
        public string tenHangHoa
        {
            get;
            set;
        }
        public string maLoaiHangHoa
        {
            get;
            set;
        }
        public string baoHanh
        {
            get;
            set;
        }
        public string maHang
        {
            get;
            set;
        }

        public string xuatXu
        {
            get;
            set;
        }

        public string namSanXuat
        {
            get;
            set;
        }

        public string maNhaCungCap
        {
            get;
            set;
        }




        public int soLuong
        {
            get;
            set;
        }


        public double giaMua
        {
            get;
            set;
        }

        public double giaBan
        {
            get;
            set;
        }
        public HangHoa()
        {

        }

        public HangHoa(string _maHangHoa, string _tenHangHoa, string _maLoaiHangHoa, string _baoHanh, string _maNhaCungCap, string _maHang, string _xuatXu, string _namSanXuat, int _soLuong, double _giaMua, double _giaBan)
        {
            this.maHangHoa = _maHangHoa;
            this.tenHangHoa = _tenHangHoa;
            this.maLoaiHangHoa = _maLoaiHangHoa;
            this.baoHanh = _baoHanh;
            this.maNhaCungCap = _maNhaCungCap;
            this.maHang = _maHang;
            this.xuatXu = _xuatXu;
            this.namSanXuat = _namSanXuat;
            this.soLuong = _soLuong;
            this.giaMua = _giaMua;
            this.giaBan = _giaBan;
        }
    }
}


