//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DTO
{
    public class HoaDonBanHang
    {
        public string maHDBH
        {
            get;
            set;
        }

        public string ngayBan
        {
            get;
            set;
        }

        public virtual string maNhanVien
        {
            get;
            set;
        }

        public string maKhachHang
        {
            get;
            set;
        }

        public double tongTien
        {
            get;
            set;
        }

        public float chietKhau
        {
            get;
            set;
        }

        public double thanhTien
        {
            get;
            set;
        }

        public HoaDonBanHang()
        {

        }

        public HoaDonBanHang(string _maHDBH, string _ngayBan, string _maNhanVien, string _maKhachHang, double _tongTien, float _chietKhau, double _thanhTien)
        {
            this.maHDBH = _maHDBH;
            this.ngayBan = _ngayBan;
            this.maNhanVien = _maNhanVien;
            this.maKhachHang = _maKhachHang;
            this.tongTien = _tongTien;
            this.chietKhau = _chietKhau;
            this.thanhTien = _thanhTien;
        }
    }
}


