//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DTO
{
    public class KhachHang
    {
        public  string maKhachHang
        {
            get;
            set;
        }

        public  string tenKhachHang
        {
            get;
            set;
        }

        public  string sdt
        {
            get;
            set;
        }

        public  string diaChi
        {
            get;
            set;
        }

        public  string ngayDangKy
        {
            get;
            set;
        }

        public  string maLoaiKhachHang
        {
            get;
            set;
        }

        public  double tienTichLuy
        {
            get;
            set;
        }

        public KhachHang()
        {

        }

        public KhachHang(string _maKhachHang, string _tenKhachHang, string _sdt, string _diaChi, string _ngayDangKy, string _maLoaiKhachHang, double _tienTichLuy)
        {
            this.maKhachHang = _maKhachHang;
            this.tenKhachHang = _tenKhachHang;
            this.sdt = _sdt;
            this.diaChi = _diaChi;
            this.ngayDangKy = _ngayDangKy;
            this.maLoaiKhachHang = _maLoaiKhachHang;
            this.tienTichLuy = _tienTichLuy;
        }
    }

}

