//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DTO
{
    public class LinhKien
    {
        public  string maLinhKien
        {
            get;
            set;
        }

        public  string tenLinhKien
        {
            get;
            set;
        }

        public  string moTa
        {
            get;
            set;
        }

        public  string maHang
        {
            get;
            set;
        }

        public  string xuatXu
        {
            get;
            set;
        }

        public  string namSanXuat
        {
            get;
            set;
        }

        public  string maNhaCungCap
        {
            get;
            set;
        }

        public LinhKien()
        {

        }
        public LinhKien(string _maLinhKien, string _tenLinhKien, string _moTa, string _maHang, string _xuatXu, string _namSanXuat, string _maNhaCungCap)
        {
            this.maLinhKien = _maLinhKien;
            this.tenLinhKien = _tenLinhKien;
            this.moTa = _moTa;
            this.maHang = _maHang;
            this.xuatXu = _xuatXu;
            this.namSanXuat = _namSanXuat;
            this.maNhaCungCap = _maNhaCungCap;
        }

    }

}

