//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DTO
{
    public class LoaiKhachHang
    {
        public  string maLoaiKhachHang
        {
            get;
            set;
        }

        public  string tenLoaiKhachHang
        {
            get;
            set;
        }

        public  float chietKhau
        {
            get;
            set;
        }

        public  double mocTien
        {
            get;
            set;
        }
        public LoaiKhachHang()
        {

        }

        public LoaiKhachHang(string _maLoaiKhachHang, string _tenLoaiKhachHang, float _chietKhau, double _mocTien)
        {
            this.maLoaiKhachHang = _maLoaiKhachHang;
            this.tenLoaiKhachHang = _tenLoaiKhachHang;
            this.chietKhau = _chietKhau;
            this.mocTien = _mocTien;
        }
    }
}


