//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DTO
{
    public class LoaiHangHoa
    {
        public  string maLoaiHangHoa
        {
            get;
            set;
        }

        public  string tenLoaiHangHoa
        {
            get;
            set;
        }

        public  string dvt
        {
            get;
            set;
        }
        public LoaiHangHoa()
        {

        }

        public LoaiHangHoa(string _maLoaiHangHoa, string _tenLoaiHangHoa, string _dvt)
        {
            this.maLoaiHangHoa = _maLoaiHangHoa;
            this.tenLoaiHangHoa = _tenLoaiHangHoa;
            this.dvt = _dvt;
        }
    }
}


