//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DTO
{
    public class MayTinh
    {
        public  string maHangHoa
        {
            get;
            set;
        }

        public  string cpu
        {
            get;
            set;
        }

        public  string hdh
        {
            get;
            set;
        }

        public  string maVGA
        {
            get;
            set;
        }

        public  string maRAM
        {
            get;
            set;
        }

        public  string diaCung
        {
            get;
            set;
        }

        public  string kichThuocManHinh
        {
            get;
            set;
        }

        public  string camUng
        {
            get;
            set;
        }

        public  string webcam
        {
            get;
            set;
        }

        public  string chatLieuVo
        {
            get;
            set;
        }

        public  string maPin
        {
            get;
            set;
        }

        public  string congGiaoTiep
        {
            get;
            set;
        }

        public  string dvd
        {
            get;
            set;
        }
        public MayTinh()
        {
            
        }
        public MayTinh(string _maHangHoa, string _tenMayTinh, string _maHang, string _cpu, string _hdh, string _maVGA, string _maRAM, string _diaCung, string _kichThuocManHinh, string _camUng, string _webcam, string _chatLieuVo, string _maPin, string _congGiaoTiep, string _dvd, string _maNhaCungCap)
        {
            this.maHangHoa = _maHangHoa;
            this.cpu = _cpu;
            this.hdh = _hdh;
            this.maVGA = _maVGA;
            this.maRAM = _maRAM;
            this.diaCung = _diaCung;
            this.kichThuocManHinh = _kichThuocManHinh;
            this.camUng = _camUng;
            this.webcam = _webcam;
            this.chatLieuVo = _chatLieuVo;
            this.maPin = _maPin;
            this.congGiaoTiep = _congGiaoTiep;
            this.dvd = _dvd;
        }
    }
}


