//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DTO
{
    public class NhaCungCap
    {
        public  string maNhaCungCap
        {
            get;
            set;
        }

        public  string tenNhaCungCap
        {
            get;
            set;
        }

        public  string sdt
        {
            get;
            set;
        }

        public  string diaChi
        {
            get;
            set;
        }
        public NhaCungCap()
        {

        }
        public NhaCungCap(string _maNhaCungCap, string _tenNhaCungCap, string _sdt, string _diaChi)
        {
            this.maNhaCungCap = _maNhaCungCap;
            this.tenNhaCungCap = _tenNhaCungCap;
            this.sdt = _sdt;
            this.diaChi = _diaChi;
        }
    }

}

