//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DTO
{
    public class NhanVien
    {
        public  string maNhanVien
        {
            get;
            set;
        }

        public  string tenNhanVien
        {
            get;
            set;
        }

        public  string sdt
        {
            get;
            set;
        }

        public  string diaChi
        {
            get;
            set;
        }

        public  string maViTri
        {
            get;
            set;
        }
        public NhanVien()
        {

        }
        public NhanVien(string _maNhanVien, string _tenNhaVien, string _sdt, string _diaChi, string _maViTri)
        {
            this.maNhanVien = _maNhanVien;
            this.tenNhanVien = _tenNhaVien;
            this.sdt = _sdt;
            this.diaChi = _diaChi;
            this.maViTri = _maViTri;
        }
    }

}

