//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DTO
{
    public class PhanQuyen
    {
        public  string maViTri
        {
            get;
            set;
        }

        public  string tenViTri
        {
            get;
            set;
        }

        public  bool thietLap
        {
            get;
            set;
        }

    }

}

