//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DTO
{
    public class Pin
    {
        public  string maPin
        {
            get;
            set;
        }

        public  string pin
        {
            get;
            set;
        }
        public Pin()
        {

        }
        public Pin(string _maPin, string _pin)
        {
            this.maPin = _maPin;
            this.pin = _pin;
        }
    }

}

