//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DTO
{
    public class RAM
    {
        public  string maRAM
        {
            get;
            set;
        }

        public  string ram
        {
            get;
            set;
        }
        public RAM()
        {

        }
        public RAM(string _maRAM, string _ram)
        {
            this.maRAM = _maRAM;
            this.ram = _ram;
        }
    }
}


