//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DTO
{
    public class VGA
    {
        public string maVGA
        {
            get;
            set;
        }

        public string vga
        {
            get;
            set;
        }
        public VGA()
        {

        }
        public VGA(string _maVGA, string _vga)
        {
            this.maVGA = _maVGA;
            this.vga = _vga;
        }
    }
}


