//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ChiTietHoaDonBanHang
{
	public virtual string maCTHDBH
	{
		get;
		set;
	}

	public virtual string maHDBH
	{
		get;
		set;
	}

	public virtual string maHangHoa
	{
		get;
		set;
	}

	public virtual int soLuong
	{
		get;
		set;
	}

	public virtual double donGia
	{
		get;
		set;
	}

	public virtual float chietKhau
	{
		get;
		set;
	}

	public virtual double thanhTien
	{
		get;
		set;
	}

}

