//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class HangHoa
{
	public virtual string maHangHoa
	{
		get;
		set;
	}

	public virtual string maLoaiHangHoa
	{
		get;
		set;
	}

	public virtual int soLuong
	{
		get;
		set;
	}

	public virtual string baoHang
	{
		get;
		set;
	}

	public virtual double giaMua
	{
		get;
		set;
	}

	public virtual double giaBan
	{
		get;
		set;
	}

}

