//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class HoaDonBanHang
{
	public virtual string maHDBH
	{
		get;
		set;
	}

	public virtual string ngayBan
	{
		get;
		set;
	}

	public virtual string maNhanVien
	{
		get;
		set;
	}

	public virtual string maKhachHang
	{
		get;
		set;
	}

	public virtual double tongTien
	{
		get;
		set;
	}

	public virtual float chietKhau
	{
		get;
		set;
	}

	public virtual double thanhTien
	{
		get;
		set;
	}

}

