//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class HoaDonMuaHang
{
	public virtual string maHDMH
	{
		get;
		set;
	}

	public virtual string ngayMua
	{
		get;
		set;
	}

	public virtual string maNhaCungCap
	{
		get;
		set;
	}

	public virtual string maNhanVien
	{
		get;
		set;
	}

	public virtual double tongTien
	{
		get;
		set;
	}

}

