//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class KhachHang
{
	public virtual string maKhachHang
	{
		get;
		set;
	}

	public virtual string tenKhachHang
	{
		get;
		set;
	}

	public virtual string sdt
	{
		get;
		set;
	}

	public virtual string diaChi
	{
		get;
		set;
	}

	public virtual string ngayDangKy
	{
		get;
		set;
	}

	public virtual string maLoaiKhachHang
	{
		get;
		set;
	}

	public virtual double tienTichLuy
	{
		get;
		set;
	}

}

