//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class LinhKien
{
	public virtual string maLinhKien
	{
		get;
		set;
	}

	public virtual string tenLinhKien
	{
		get;
		set;
	}

	public virtual string moTa
	{
		get;
		set;
	}

	public virtual string maHang
	{
		get;
		set;
	}

	public virtual string xuatXu
	{
		get;
		set;
	}

	public virtual string namSanXuat
	{
		get;
		set;
	}

	public virtual string maNhaCungCap
	{
		get;
		set;
	}

}

