//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class LoaiKhachHang
{
	public virtual string maLoaiKhachHang
	{
		get;
		set;
	}

	public virtual string tenLoaiKhachHang
	{
		get;
		set;
	}

	public virtual float chietKhau
	{
		get;
		set;
	}

	public virtual double mocTien
	{
		get;
		set;
	}

}

