//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class LoaiHangHoa
{
	public virtual string maLoaiHangHoa
	{
		get;
		set;
	}

	public virtual string tenLoaiHangHoa
	{
		get;
		set;
	}

	public virtual string dvt
	{
		get;
		set;
	}

}

