//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class MayTinh
{
	public virtual string maMayTinh
	{
		get;
		set;
	}

	public virtual string tenMayTinh
	{
		get;
		set;
	}

	public virtual string maHang
	{
		get;
		set;
	}

	public virtual string cpu
	{
		get;
		set;
	}

	public virtual string hdh
	{
		get;
		set;
	}

	public virtual string maVGA
	{
		get;
		set;
	}

	public virtual string maRAM
	{
		get;
		set;
	}

	public virtual string diaCung
	{
		get;
		set;
	}

	public virtual string kichThuocManHinh
	{
		get;
		set;
	}

	public virtual string camUng
	{
		get;
		set;
	}

	public virtual string webcam
	{
		get;
		set;
	}

	public virtual string chatLieuVo
	{
		get;
		set;
	}

	public virtual string maPin
	{
		get;
		set;
	}

	public virtual string congGiaoTiep
	{
		get;
		set;
	}

	public virtual string dvd
	{
		get;
		set;
	}

	public virtual string maNhaCungCap
	{
		get;
		set;
	}

}

