//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class NhanVien
{
	public virtual string maNhanVien
	{
		get;
		set;
	}

	public virtual string tenNhanVien
	{
		get;
		set;
	}

	public virtual string sdt
	{
		get;
		set;
	}

	public virtual string diaChi
	{
		get;
		set;
	}

	public virtual string maViTri
	{
		get;
		set;
	}

}

