//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TaiKhoan
{
	public virtual string maNhanVien
	{
		get;
		set;
	}

	public virtual string taiKhoan
	{
		get;
		set;
	}

	public virtual string matKhau
	{
		get;
		set;
	}

}

